### ISSUE TITLE
Address TODO comment in code: FactoryRegistration.Resolve should add the created object into the pool of created objects

### ISSUE THREAD

**Issue by craigfowler** [gasparnagy/BoDi#10]
In the class FactoryRegistration, Resolve method, there is a TODO comment indicating that the created instance should perhaps be added to the pool of created instances.

This would mean that the created instance is cached in the container (future resolutions using the same key would return the same instance), and the created instance could also be disposed along with the container.

I believe that this is indeed a desirable feature and it should be implemented.

In order to preserve backwards compatibility with the current behaviour, the method `RegisterFactoryAs` could be extended with a new overload which accepts a boolean indicating whether the object should be pooled, with a default value of `false`.

I am open to discussion on whether it is important or not to support the current behaviour (each resolve call gets a new instance, and instances are not disposed by the container) or whether that behaviour should simply be considered a 'bug'.  Does anybody rely on it?

**Comment by craigfowler** [comment]
In fact - it turns out that this is not a problem after all.  I see no reason that the resolved instance needs to be added to any kind of pool.  In line with the test at **BoDi.Tests.RegisterFactoryDelegateTests.ShouldReturnTheSameIfResolvedTwice** it is clear that the instance is already cached and reused when resolving for a second time.  I instead propose removing this comment (line 404 of BoDi.cs):

```csharp
//TODO: store result object in pool?
```

**Comment by gasparnagy** [comment]
removed. thx.
