### ISSUE TITLE
Formally adopt semantic versioning and ensure all NuGet releases are appropriately tagged

### ISSUE THREAD

**Issue by craigfowler** [gasparnagy/BoDi#11]
It may be that BoDi has already adopted [semantic versioning], it is somewhat difficult to tell because there is a NuGet release: **1.3.0** which is very difficult to pin down to a specific commit.

[semantic versioning]: http://semver.org/

Going by the NuGet timestamp for that release (27th June 2017), it could be based on commit `599d7fef80b5049e9009360520b821223bca3887` or anything earlier; there's no specific activity which corresponds directly to that release date.  More importantly, there is no git tag for 1.3.0 so it's hard to tell.  To be more reusable for other open source projects, I would recommend adopting a policy of ensuring that all NuGet releases are tagged appropriately.

**Comment by craigfowler** [comment]
As a follow-up:  Could I ask which commit represents v1.3.0 (that is, the software that was released as 1.3.0 on NuGet)?  Was it `599d7fef80b5049e9009360520b821223bca3887` or was it a different commit?  I'd like to tag it in my own repo for purposes of maintaining compatibility.

Thanks

**Comment by gasparnagy** [comment]
oh. i supposed to add a tag for it. i will check

**Comment by gasparnagy** [comment]
The commit and tag was missing... Now pushed.
