### ISSUE TITLE
Allow registration of types where ctor have parameters

### ISSUE THREAD

**Issue by TotalTest** [gasparnagy/BoDi#25]
I'm using the latest version of SpecFlow (which in turn has the latest version of BoDi =. 1.4.1).
I would like to utulise the 'RegisterTypeAs' way of registering but the problem is the type I am registering has a ctor with parameters.

e.g. I have the following sample

_container.RegisterTypeAs<WebDriver, ICustomWebDriver>();

But the type WebDriver has a ctor that needs parameters. 

The use case of doing it this way is so if I register multiple custom drivers they only get resolved (via constructor) for the binding classes that use them for a particular test. (i.e. not all tests need both drivers but some may).

Essentially something similar to Autofac (taken from their site):

// Using a NAMED parameter:
builder.RegisterType<ConfigReader>()
       .As<IConfigReader>()
       .WithParameter("configSectionName", "sectionName");

// Using a TYPED parameter:
builder.RegisterType<ConfigReader>()
       .As<IConfigReader>()
       .WithParameter(new TypedParameter(typeof(string), "sectionName"));

**Comment by gasparnagy** [comment]
BoDi is a simple DI framework, so definitely it will have a smaller feature set than tools, like Autofac. SpecFlow can be configured to use Autofac (see [SpecFlow.Autofac NuGet package](https://www.nuget.org/packages/SpecFlow.Autofac)) for complex cases.

In you case, you can still use the `RegisterFactoryAs<TInterface>(Func<IObjectContainer, TInterface> factoryDelegate, string name = null)` to register classes with special constructor parameters, like `_container.RegisterFactoryAs<ICustomWebDriver>((cont) => new WebDriver("sectionName"));`.

I hope this helps. Please reopen the issue if the solution does not work.
