### ISSUE TITLE
Propose moving away from 'single source file' as a design guideline

### ISSUE THREAD

**Issue by craigfowler** [gasparnagy/BoDi#9]
BoDi looks like a great project, but I'm not sure I agree with the design guideline that everything is contained within a single source file.

With NuGet being so prevalent (and BoDi having NuGet packages available) it's very easy to include the container as a NuGet package.  However, for the purpose of maintainability, having all of the source in a single file is somewhat inconvenient.

I appreciate that for SpecFlow it's going to be desirable to do that because - I presume - BoDi isn't included as a 3rd party dependency but rather the whole source file is just copy-pasted into SpecFlow's source.  Given the extremely close relationships between the projects this is reasonable for SpecFlow.

For other projects which might want to reuse BoDi, that can be less optimal because (for example) upgrading BoDi is impossible without a fresh build of the dependent project.

I'm open to discussion on this.  My rationale is quite simply that I'd like to reuse BoDi for my own testing-related project (which needs a small DI container).  I think I also would like to make a few enhancements, but if I make more than just trivial changes then I'm going to want to bust it up into single-file-per-class.

**Comment by craigfowler** [comment]
If this is acceptable, then along with it, the changelog could be dropped from the file comment header.  If a changelog in source control is desired then it could be moved it a single text file (mentioned in the header).  Or - even better - host the changelog on Github via it's "releases" functionality (each release notes the changes which went in).

**Comment by craigfowler** [comment]
Something which might allow "the best of both worlds" might be to include BoDi within **SpecFlow** (and only within SpecFlow) as a [git submodule]?  This has its ups and downs (it's quite easy to shoot yourself in the foot if you go about it the wrong way). But - it is one way in which the project can still follow single-type-per-file design, yet be included easily within SpecFlow without needing to be compiled into a separate assembly.

[git submodule]: https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by gasparnagy** [comment]
Together with the .NET Core support of SpecFlow. We plan to move away from source code embedding this into SpecFlow and will use it as a normal NuGet dependency. 
That decision made sense at that time, but had to be revisited I agree.
Once we make that step with SpecFlow, we can do splitting refactoring the codebase more easily. Let's wait for that.
